// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oryx.Saas.Framework.Business;

namespace Oryx.Saas.Framework.Migrations
{
    [DbContext(typeof(SaasServiceDbContext))]
    partial class SaasServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavIco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaasAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppHeader");
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppStruct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppHeaderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaasAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppHeaderId");

                    b.ToTable("AppStructs");
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppStructItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppHeaderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppStructId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaasAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppHeaderId");

                    b.HasIndex("AppStructId");

                    b.ToTable("AppStructItem");
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.SaasAdminConsume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaasAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaasAdminConsume");
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.SaasAdminWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaasAdminId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SaasAdminWallet");
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppStruct", b =>
                {
                    b.HasOne("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppHeader", "AppHeader")
                        .WithMany("AppStructs")
                        .HasForeignKey("AppHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppStructItem", b =>
                {
                    b.HasOne("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppHeader", "AppHeader")
                        .WithMany()
                        .HasForeignKey("AppHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oryx.Saas.Framework.Business.ServiceSection.SaasServiceSection.ServiceEntities.AppStruct", "AppStruct")
                        .WithMany("AppStructItem")
                        .HasForeignKey("AppStructId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
